title: "CSE 80: Linux and the Command Line"
email: scauligi@eng.ucsd.edu
description: > # this means to ignore newlines until "url:"
  This 2-unit course aims to teach some essential skills for all Computer
  Scientists that you'll use throughout your classes, into industry and beyond.
  The class approaches the Unix Command Line Interface (CLI) as a primary tool
  for computing, and covers techniques that turn the CLI into a powerful,
  flexible and extensible toolkit, adding useful historical context along the way.
url: "https://cse80.github.io" # the base hostname & protocol for your site

timezone: America/Los_Angeles

permalink: none

collections:
  commands:
    output: true
    permalink: /commands/:title
  syllabus:
  updates:
  lectures:
    output: true

defaults:
  - scope:
      type: lectures
    values:
      layout: lecture
  - scope:
      path: "_lectures/f16"
    values:
      category: f16
  - scope:
      path: "_updates/f16"
    values:
      category: f16
  - scope:
      path: "_updates/w16"
    values:
      category: w16
  - scope:
      type: syllabus
    values:
      layout: syllabus
  - scope:
      path: "_syllabus/f16"
    values:
      category: f16
  - scope:
      path: "_lectures/w17"
    values:
      category: w17
  - scope:
      path: "_updates/w17"
    values:
      category: w17
  - scope:
      path: "_syllabus/w17"
    values:
      category: w17
  - scope:
      path: "_lectures/su17"
    values:
      category: su17
  - scope:
      path: "_updates/su17"
    values:
      category: su17
  - scope:
      path: "_syllabus/su17"
    values:
      category: su17
  - scope:
      type: commands
    values:
      layout: reference
  - scope:
      path: "_commands/basics"
    values:
      category: basics
  - scope:
      path: "_commands/tutorials"
    values:
      category: tutorials
  - scope:
      path: "_commands/shells"
    values:
      category: shells
  - scope:
      path: "_commands/scripting"
    values:
      category: scripting
  - scope:
      path: "_commands/tools"
    values:
      category: tools
  - scope:
      path: "_commands/editors"
    values:
      category: editors
  - scope:
      path: "_commands/toys"
    values:
      category: toys
  - scope:
      path: "_commands/ubuntu"
    values:
      category: ubuntu
  - scope:
      path: "_commands/os_x"
    values:
      category: os_x

command_categories: ["basics"]
#command_categories: ["basics", "tutorials", "shells", "scripting", "tools", "editors", "toys", "ubuntu", "os_x"]

# Build settings
markdown: kramdown

# This is a bit of a hack, since we're using remark, which expects
# to render markdown itself, we need to prevent jekyll from picking
# it up and parsing it, however we would still like to use the templating
# features of jekyll so that we can just write slides alone, in a
# markdown file. Thus we override the extensions list so that jekyll does
# not treat .markdown files as markdown.
markdown_ext: "mkdown,mkdn,mkd,md"

# Needed for Travis
exclude: [vendor]
